#!/usr/bin/env python3
"""
Translate all 262 original war names and participation fields to Spanish.
"""
import csv

INPUT_CSV = 'site/data/PoppyDataCSV.csv'
OUTPUT_CSV = 'site/data/PoppyDataCSV.csv'

# Complete translation map for war names (English -> Spanish)
WAR_NAME_TRANSLATIONS = {
    "War in Eastern Ukraine": "Guerra en el este de Ucrania",
    "Sectarian Conflict in the Central African Republic": "Conflicto sectario en la República Centroafricana",
    "South Sudan Civil War": "Guerra civil de Sudán del Sur",
    "Syrian Civil War": "Guerra civil siria",
    "Yemen vs Al-Quaeda": "Yemen vs Al-Qaeda",
    "Nigerian Govt vs Boko Haram": "Nigeria vs Boko Haram",
    "Waziristan conflict": "Conflicto de Waziristán",
    "Kivu Conflict": "Conflicto de Kivu",
    "Iraqi Insurgency": "Insurgencia iraquí",
    "Afghanistan War": "Guerra de Afganistán",
    "Al-Qaida vs United States and allies": "Al-Qaeda vs Estados Unidos y aliados",
    "Russia vs Chechnyan Secessionists and the Caucasus Emirate": "Rusia vs separatistas chechenos y el Emirato del Cáucaso",
    "Algeria Govt vs Islamic rebels, GIA, AIS, AQIM": "Argelia vs rebeldes islámicos, GIA, AIS, AQIM",
    "Indian Govt vs Maoist Guerillas": "India vs guerrillas maoístas",
    "India vs Pakistan, Kashmir Dispute": "India vs Pakistán, disputa de Cachemira",
    "Turkey Gov vs Kurdistan Guerilla": "Turquía vs guerrilla kurda",
    "Sudan Govt vs Militias": "Sudán vs milicias",
    "Somali Civil War": "Guerra civil somalí",
    "Uganda Civil War": "Guerra civil de Uganda",
    "Mozambique Govt vs RENAMO and FRELIMO": "Mozambique vs RENAMO y FRELIMO",
    "Ethiopia vs Oromia rebels": "Etiopía vs rebeldes de Oromía",
    "Ethiopian Govt vs Ogadeni Rebels": "Etiopía vs rebeldes de Ogadén",
    "Philippines Govt vs Mindanao Guerillas": "Filipinas vs guerrillas de Mindanao",
    "Philippine Govt vs CPP Guerrilla": "Filipinas vs guerrilla del CPP",
    "Colombia Govt vs Guerillas Farc and ELN": "Colombia vs guerrillas FARC y ELN",
    "Burmese Govt vs Separatist Guerillas": "Birmania vs guerrillas separatistas",
    "Mexican Drug War": "Guerra contra el narcotráfico en México",
    "Israel vs Palestine": "Israel vs Palestina",
    "Libyan Civil War": "Guerra civil libia",
    "Tajikistan Govt vs Opposition": "Tayikistán vs oposición",
    "Senegal Civil War": "Guerra civil de Senegal",
    "Iran vs rebel groups": "Irán vs grupos rebeldes",
    "Chad Civil War": "Guerra civil de Chad",
    "Peruvian Govt vs Sendero Luminoso and MRTA": "Perú vs Sendero Luminoso y MRTA",
    "Sri Lankan Govt vs Tamil Militants": "Sri Lanka vs militantes tamiles",
    "Burundi Civil War": "Guerra civil de Burundi",
    "Nepal Civil War": "Guerra civil de Nepal",
    "Southern Lebanon War": "Guerra del sur del Líbano",
    "Indonesia Govt vs Aceh Liberation movement": "Indonesia vs movimiento de liberación de Aceh",
    "Ivorian Civil War ": "Guerra civil de Costa de Marfil",
    "Ituri Conflict": "Conflicto de Ituri",
    "Iraq vs United States led coalition": "Irak vs coalición liderada por EE.UU.",
    "First and Second Congo Wars": "Primera y segunda guerras del Congo",
    "Liberia Civil War": "Guerra civil de Liberia",
    "Congo Brazzaville Civil War": "Guerra civil del Congo (Brazzaville)",
    "Angolan Govt vs UNITA Guerilla": "Angola vs guerrilla UNITA",
    "Sierra Leone Civil War": "Guerra civil de Sierra Leona",
    "Eritrea vs Ethiopia": "Eritrea vs Etiopía",
    "Afghanistan Civil War": "Guerra civil de Afganistán",
    "Yugoslavia vs NATO Forces and UCK Guerilla": "Yugoslavia vs OTAN y guerrilla UCK",
    "Indonesian Govt vs Fretilin - East Timor": "Indonesia vs Fretilin - Timor Oriental",
    "Cambodian Govt vs Khmer Rouge": "Camboya vs Jemeres Rojos",
    "Northern Ireland, The Troubles": "Irlanda del Norte, Los Troubles",
    "Iraq vs Kurdistan": "Irak vs Kurdistán",
    "Iraq Government vs SCIRI": "Gobierno de Irak vs SCIRI",
    "Iranian Govt vs KDPI": "Irán vs KDPI",
    "Bosnian Govt vs Serbian and Croatian Insurgents": "Bosnia vs insurgentes serbios y croatas",
    "Croatia vs Serbian Irregulars": "Croacia vs irregulares serbios",
    "Guatemalan Civil War": "Guerra civil de Guatemala",
    "North Yemen vs Secessionists": "Yemen del Norte vs secesionistas",
    "Nagorno-Karabakh War": "Guerra de Nagorno-Karabaj",
    "Rwanda Civil War ": "Guerra civil de Ruanda",
    "Burmese Govt vs Communist Guerillas": "Birmania vs guerrillas comunistas",
    "Georgian Civil War": "Guerra civil de Georgia",
    "Indian Govt vs Sikh insurgents": "India vs insurgentes sij",
    "Serbian Govt. vs Croatian irregulars": "Serbia vs irregulares croatas",
    "First Gulf War": "Primera Guerra del Golfo",
    "El Salvador Gvt vs FMLN Guerrillas": "El Salvador vs guerrillas del FMLN",
    "Ethiopian Government vs EPRDF": "Etiopía vs EPRDF",
    "Ethiopia vs Eritrean Separatists ELF/EPLF": "Etiopía vs separatistas eritreos ELF/EPLF",
    "Nicaragua Govt vs Contras": "Nicaragua vs Contras",
    "Lebanese Civil War": "Guerra civil del Líbano",
    "Sri Lanka Govt vs JVP": "Sri Lanka vs JVP",
    "Panama Coup and United States Invasion": "Golpe de Panamá e invasión de EE.UU.",
    "Romanian Revolution": "Revolución rumana",
    "Western Sahara War": "Guerra del Sáhara Occidental",
    "Iran vs Iraq": "Irán vs Irak",
    "South Africa vs ANC": "Sudáfrica vs ANC",
    "Sino-Vietnamese War": "Guerra sino-vietnamita",
    "Namibia vs South Africa": "Namibia vs Sudáfrica",
    "Chadian-Lybian War (Aouzou Strip)": "Guerra Chad-Libia (Franja de Aouzou)",
    "South Yemen Coup": "Golpe de Yemen del Sur",
    "Falklands War": "Guerra de las Malvinas",
    "Syrian Govt vs Muslim Brotherhood": "Siria vs Hermanos Musulmanes",
    "Thai Govt vs CPT": "Tailandia vs CPT",
    "Nicaraguan Gvt vs Sandinistas": "Nicaragua vs Sandinistas",
    "Uganda vs Tanzania": "Uganda vs Tanzania",
    "Iranian Revolution": "Revolución iraní",
    "Rhodesian Government vs ZANU,ZAPU,PF": "Rodesia vs ZANU, ZAPU, PF",
    "Vietnam vs Cambodia (Kampuchea)": "Vietnam vs Camboya (Kampuchea)",
    "Indonesian annexation of West Papua": "Anexión indonesia de Papúa Occidental",
    "Balochistan Insurgency": "Insurgencia en Baluchistán",
    "Argentina: Civil War and Dirty War": "Argentina: Guerra civil y Guerra Sucia",
    "Chinese Cultural Revolution": "Revolución Cultural China",
    "Cambodian Civil War": "Guerra civil de Camboya",
    "Vietnam War": "Guerra de Vietnam",
    "Angolan War of Independence": "Guerra de independencia de Angola",
    "Turko Cypriot War": "Guerra turco-chipriota",
    "Mozambique War of Independence": "Guerra de independencia de Mozambique",
    "Chilean MIlitary Coup": "Golpe militar en Chile",
    "Yom Kippur War": "Guerra de Yom Kipur",
    "Guinea Bissau War of Independence": "Guerra de independencia de Guinea-Bisáu",
    "Laos Civil War": "Guerra civil de Laos",
    "Hutu Rebellion": "Rebelión hutu",
    "Sudan Government vs Insurgents": "Sudán vs insurgentes",
    "Bangladesh War": "Guerra de Bangladés",
    "Second Kashmir War": "Segunda guerra de Cachemira",
    "Israel vs Egypt": "Israel vs Egipto",
    "Nigerian Civil War": "Guerra civil de Nigeria",
    "North Yemen Civil War": "Guerra civil de Yemen del Norte",
    "First Kurdish_Iraqi War": "Primera guerra kurdo-iraquí",
    "Football War Honduras vs El Salvador": "Guerra del Fútbol Honduras vs El Salvador",
    "The Six Day War": "La Guerra de los Seis Días",
    "Dominican Republic Coup": "Golpe de la República Dominicana",
    "Congo Crisis": "Crisis del Congo",
    "First Rwanda Civil War": "Primera guerra civil de Ruanda",
    "Vietnam Civil War": "Guerra civil de Vietnam",
    "Sino-Indian War": "Guerra sino-india",
    "Algerian War of Independece": "Guerra de independencia de Argelia",
    "Bizerte Crisis": "Crisis de Bizerta",
    "Cameroonian Govt vs UPC": "Camerún vs UPC",
    "Indonesia vs PRRI, Permesta and Darul Islam": "Indonesia vs PRRI, Permesta y Darul Islam",
    "Cuban Revolution": "Revolución cubana",
    "1959 Mosul uprising in Iraq": "Levantamiento de Mosul de 1959 en Irak",
    "Cameroon War of Independence": "Guerra de independencia de Camerún",
    "Tibetan Uprising": "Levantamiento tibetano",
    "First Lebanese War": "Primera guerra del Líbano",
    "La Violencia": "La Violencia",
    "Malayan Civil War": "Guerra civil malaya",
    "Soviet Invasion of Hungary": "Invasión soviética de Hungría",
    "Sinai War": "Guerra del Sinaí",
    "Kenya, Mau-Mau vs UK": "Kenia, Mau-Mau vs Reino Unido",
    "Tunisian war of Independence": "Guerra de independencia de Túnez",
    "Moroccan War of Independence": "Guerra de independencia de Marruecos",
    "Taiwan Strait Crisis": "Crisis del Estrecho de Taiwán",
    "First Indochina War Comm. vs France": "Primera guerra de Indochina vs Francia",
    "Philippines, Huk rebels vs Govt": "Filipinas, rebeldes Huk vs gobierno",
    "Korean War": "Guerra de Corea",
    "Bolivian Revolution": "Revolución boliviana",
    "Indian Govt vs Communist Rebels CPI": "India vs rebeldes comunistas CPI",
    "Soviet Union vs Baltic Partisans": "Unión Soviética vs partisanos bálticos",
    "Indonesian Govt vs Republic of South Moluccas": "Indonesia vs República de las Molucas del Sur",
    "Third Sino-Tibetan War": "Tercera guerra sino-tibetana",
    "Arab-Israeli War": "Guerra árabe-israelí",
    "Cheju Rebellion in South Korea": "Rebelión de Jeju en Corea del Sur",
    "Chinese Civil War": "Guerra civil china",
    "Greece Civil War": "Guerra civil de Grecia",
    "Costa Rican Civil War": "Guerra civil de Costa Rica",
    "Yemeni Imamate War": "Guerra del Imanato de Yemen",
    "First Kashmir War": "Primera guerra de Cachemira",
    "Civil War in Mandatory Palestine": "Guerra civil en el Mandato de Palestina",
    "Telangana Rebellion and Indo-Hyderabad War": "Rebelión de Telangana y guerra indo-hyderabadí",
    "Indian Partition Communal Violence": "Violencia comunal de la Partición de la India",
    "Taiwanese revolt": "Revuelta taiwanesa",
    "Madagascar Rebellion": "Rebelión de Madagascar",
    "Paraguayan Gvt vs Rebels": "Paraguay vs rebeldes",
    "Poland and Soviet Union vs Ukrainian Partisans": "Polonia y Unión Soviética vs partisanos ucranianos",
    "Indonesian Independence": "Independencia de Indonesia",
    "World War II": "Segunda Guerra Mundial",
    "Franco-Thai War": "Guerra franco-tailandesa",
    "Third Sino-Japanese War": "Tercera guerra sino-japonesa",
    "The Winter War in Finland": "La Guerra de Invierno en Finlandia",
    "The battle of Khalkhin Gol": "La batalla de Jaljin Gol",
    "Spanish Civil War": "Guerra Civil Española",
    "Arab revolt in Mandatory Palestine": "Revuelta árabe en el Mandato de Palestina",
    "Second British-Waziristan": "Segunda guerra británica en Waziristán",
    "Changkufeng Incident": "Incidente de Changkufeng",
    "Italo-Ethiopian War": "Guerra italo-etíope",
    "Chaco War": "Guerra del Chaco",
    "Communists vs Koumintang": "Comunistas vs Kuomintang",
    "Saudi-Yemeni War": "Guerra saudí-yemení",
    "Spanish Socialists vs Govt": "Socialistas españoles vs gobierno",
    "Xinjiang Muslim Revolt": "Revuelta musulmana de Xinjiang",
    "Manchurian War": "Guerra de Manchuria",
    "La Matanza ": "La Matanza",
    "Brazilian Revolt": "Revuelta brasileña",
    "Aprista Revolt in Peru": "Revuelta aprista en Perú",
    "Saya San Rebellion": "Rebelión de Saya San",
    "Senussi Orden vs Italy": "Orden Senussi vs Italia",
    "The Yen Bai Uprising": "El levantamiento de Yen Bai",
    "Ikhwan Revolt": "Revuelta Ikhwan",
    "Kuomintang vs Warlords": "Kuomintang vs señores de la guerra",
    "Escobar Rebellion": "Rebelión de Escobar",
    "Sino-Soviet war": "Guerra sino-soviética",
    "Second Afghan Anti-Reform War": "Segunda guerra antirreformista afgana",
    "The Cristero War": "La Guerra Cristera",
    "Kuomintang vs Gansu Rebels": "Kuomintang vs rebeldes de Gansu",
    "Northern Expedition": "Expedición del Norte",
    "Druze revolt": "Revuelta drusa",
    "Third Chinese Warlord War": "Tercera guerra de señores de la guerra china",
    "Third Rif War": "Tercera guerra del Rif",
    "Afghan rebels vs govt": "Rebeldes afganos vs gobierno",
    "Nejd-Hejaz Wars": "Guerras de Néyed-Hiyaz",
    "Honduras Coup": "Golpe de Honduras",
    "Soviet-Turkestan War": "Guerra soviético-turquestana",
    "Second Chinese Warlord War": "Segunda guerra de señores de la guerra china",
    "Moplah Riots in Kerala": "Disturbios Moplah en Kerala",
    "Ireland freestaters vs Irregulars": "Estado Libre de Irlanda vs Irregulares",
    "Blackshirts vs Leftists": "Camisas Negras vs izquierdistas",
    "Second Greco Turkish War": "Segunda guerra greco-turca",
    "Russian Revolution and Civil War": "Revolución rusa y guerra civil",
    "Kronstadt Rebellion": "Rebelión de Kronstadt",
    "Conquest of Mongolia": "Conquista de Mongolia",
    "Green Rebellion": "Rebelión Verde",
    "Iraq vs UK": "Irak vs Reino Unido",
    "Turkish War of Independence": "Guerra de independencia de Turquía",
    "First Chinese Warlord War": "Primera guerra de señores de la guerra china",
    "Franco-Syrian war": "Guerra franco-siria",
    "Lithuanian-Polish War": "Guerra lituano-polaca",
    "Hungary Civil War": "Guerra civil de Hungría",
    "Polish-Soviet War": "Guerra polaco-soviética",
    "First British-Waziristan War": "Primera guerra británica en Waziristán",
    "Estonian Liberation War": "Guerra de liberación de Estonia",
    "Latvian Liberation": "Liberación de Letonia",
    "Caco Revolt": "Revuelta Caco",
    "Mexican Revolution": "Revolución mexicana",
    "The Dervish State vs Ethiopia, Britain and Italy": "El Estado Derviche vs Etiopía, Gran Bretaña e Italia",
    "Sparticist Rising": "Levantamiento espartaquista",
    "Hungarian Romanian War": "Guerra húngaro-rumana",
    "Third Anglo-Afghan War": "Tercera guerra anglo-afgana",
    "Finnish Civil War": "Guerra civil de Finlandia",
    "Second Sino-Tibetan": "Segunda guerra sino-tibetana",
    "Southern China Revolt": "Revuelta del sur de China",
    "World War I": "Primera Guerra Mundial",
    "Russia-Turkestan": "Rusia-Turquestán",
    "Chinese Govt vs Bai Lang Rebels": "China vs rebeldes Bai Lang",
    "2nd Balkan War": "Segunda Guerra Balcánica",
    "Kuomintang vs Chinese Army": "Kuomintang vs ejército chino",
    "Moro Rebellion": "Rebelión moro",
    "1st Balkan War": "Primera Guerra Balcánica",
    "Paraguay Coups": "Golpes de Estado en Paraguay",
    "Italo-Turkish War": "Guerra italo-turca",
    "First Sino-Tibetan War": "Primera guerra sino-tibetana",
    "Cuba vs Partido Independiente de Color": "Cuba vs Partido Independiente de Color",
    "Chinese Revolution": "Revolución china",
    "Asir-Yemen Revolt": "Revuelta de Asir-Yemen",
    "French Conquest of Wadai Sultanate": "Conquista francesa del Sultanato de Wadai",
    "The second Rif War": "La segunda guerra del Rif",
    "Portugese war against Dembos": "Guerra portuguesa contra Dembos",
    "Ma al-Aynayn's Anti-Colonial Insurgency": "Insurgencia anticolonial de Ma al-Aynayn",
    "Korean guerilla war against Japanese occupation": "Guerrilla coreana contra la ocupación japonesa",
    "Iranian Constitution War": "Guerra constitucional de Irán",
    "Morocco unrest": "Disturbios en Marruecos",
    "Romanian Peasant Revolt": "Revuelta campesina rumana",
    "Fourth Central American war": "Cuarta guerra centroamericana",
    "Dutch-Achinese War": "Guerra holandesa-achinesa",
    "Sokoto and UK vs Mahdist Revolt": "Sokoto y Reino Unido vs revuelta mahdista",
    "Zulu Rebellion": "Rebelión zulú",
    "Third Central American war": "Tercera guerra centroamericana",
    "Russian Revolution": "Revolución rusa",
    "Maji Maji revolt": "Revuelta Maji Maji",
    "Russo-Japanese war": "Guerra ruso-japonesa",
    "Southwest African Revolt": "Revuelta del África del Sudoeste",
    "Uruguay Civil War": "Guerra civil de Uruguay",
    "Second Yemen Rebellion": "Segunda rebelión de Yemen",
    "Uprisings in Colonial Angola": "Levantamientos en Angola colonial",
    "Ilinden Uprising": "Levantamiento de Ilinden",
    "The War of a Thousand Days": "La Guerra de los Mil Días",
    "Philippine insurrection": "Insurrección filipina",
    "Second Boer war": "Segunda Guerra Bóer",
    "The Boxer Rebellion": "La Rebelión de los Bóxers",
    "Sino-Russian War": "Guerra sino-rusa",
}

# Translation map for common participation/country terms
COUNTRY_TRANSLATIONS = {
    "United States": "Estados Unidos",
    "United Kingdom": "Reino Unido",
    "Soviet Union": "Unión Soviética",
    "Germany": "Alemania",
    "France": "Francia",
    "Japan": "Japón",
    "China": "China",
    "Italy": "Italia",
    "Spain": "España",
    "Russia": "Rusia",
    "Turkey": "Turquía",
    "Greece": "Grecia",
    "Poland": "Polonia",
    "Hungary": "Hungría",
    "Romania": "Rumanía",
    "Finland": "Finlandia",
    "Estonia": "Estonia",
    "Latvia": "Letonia",
    "Lithuania": "Lituania",
    "Ireland": "Irlanda",
    "Northern Ireland": "Irlanda del Norte",
    "Egypt": "Egipto",
    "Libya": "Libia",
    "Morocco": "Marruecos",
    "Tunisia": "Túnez",
    "Algeria": "Argelia",
    "Ethiopia": "Etiopía",
    "Eritrea": "Eritrea",
    "Somalia": "Somalia",
    "Sudan": "Sudán",
    "South Sudan": "Sudán del Sur",
    "Nigeria": "Nigeria",
    "Uganda": "Uganda",
    "Kenya": "Kenia",
    "Tanzania": "Tanzania",
    "Mozambique": "Mozambique",
    "Angola": "Angola",
    "South Africa": "Sudáfrica",
    "Namibia": "Namibia",
    "Zimbabwe": "Zimbabue",
    "Rhodesia": "Rodesia",
    "Congo": "Congo",
    "Rwanda": "Ruanda",
    "Burundi": "Burundi",
    "Chad": "Chad",
    "Cameroon": "Camerún",
    "Sierra Leone": "Sierra Leona",
    "Liberia": "Liberia",
    "Senegal": "Senegal",
    "Madagascar": "Madagascar",
    "India": "India",
    "Pakistan": "Pakistán",
    "Bangladesh": "Bangladés",
    "Sri Lanka": "Sri Lanka",
    "Nepal": "Nepal",
    "Myanmar": "Myanmar",
    "Burma": "Birmania",
    "Thailand": "Tailandia",
    "Vietnam": "Vietnam",
    "Cambodia": "Camboya",
    "Laos": "Laos",
    "Indonesia": "Indonesia",
    "Philippines": "Filipinas",
    "Malaysia": "Malasia",
    "North Korea": "Corea del Norte",
    "South Korea": "Corea del Sur",
    "Korea": "Corea",
    "Taiwan": "Taiwán",
    "Tibet": "Tíbet",
    "Mongolia": "Mongolia",
    "Iran": "Irán",
    "Iraq": "Irak",
    "Syria": "Siria",
    "Lebanon": "Líbano",
    "Jordan": "Jordania",
    "Israel": "Israel",
    "Palestine": "Palestina",
    "Saudi Arabia": "Arabia Saudita",
    "Yemen": "Yemen",
    "Afghanistan": "Afganistán",
    "Tajikistan": "Tayikistán",
    "Mexico": "México",
    "Guatemala": "Guatemala",
    "El Salvador": "El Salvador",
    "Honduras": "Honduras",
    "Nicaragua": "Nicaragua",
    "Costa Rica": "Costa Rica",
    "Panama": "Panamá",
    "Cuba": "Cuba",
    "Dominican Republic": "República Dominicana",
    "Haiti": "Haití",
    "Colombia": "Colombia",
    "Venezuela": "Venezuela",
    "Peru": "Perú",
    "Bolivia": "Bolivia",
    "Paraguay": "Paraguay",
    "Argentina": "Argentina",
    "Brazil": "Brasil",
    "Chile": "Chile",
    "Uruguay": "Uruguay",
    "Ecuador": "Ecuador",
    "Croatia": "Croacia",
    "Bosnia": "Bosnia",
    "Serbia": "Serbia",
    "Georgia": "Georgia",
    "Armenia": "Armenia",
    "Azerbaijan": "Azerbaiyán",
    "Cyprus": "Chipre",
    "NATO": "OTAN",
    "UK": "Reino Unido",
    "US": "EE.UU.",
    "Allies": "Aliados",
    "Axis": "Eje",
    "Britain": "Gran Bretaña",
    "Portugal": "Portugal",
    "Netherlands": "Países Bajos",
    "Belgium": "Bélgica",
    "Austria": "Austria",
    "Czechoslovakia": "Checoslovaquia",
    "Yugoslavia": "Yugoslavia",
    "Bulgaria": "Bulgaria",
    "Albania": "Albania",
    "Central African Republic": "Rep. Centroafricana",
    "Guinea Bissau": "Guinea-Bisáu",
    "East Timor": "Timor Oriental",
    "Western Sahara": "Sáhara Occidental",
}


def translate_participation(text):
    """Translate country/participation names from English to Spanish."""
    if not text:
        return text
    result = text
    # Sort by length descending to avoid partial replacements
    sorted_terms = sorted(COUNTRY_TRANSLATIONS.keys(), key=len, reverse=True)
    for eng, spa in [(k, COUNTRY_TRANSLATIONS[k]) for k in sorted_terms]:
        result = result.replace(eng, spa)
    return result


def main():
    with open(INPUT_CSV) as f:
        reader = csv.DictReader(f)
        fieldnames = reader.fieldnames
        rows = list(reader)

    translated = 0
    participation_translated = 0
    
    for row in rows:
        # Skip UCDP entries (already in Spanish)
        if 'UCDP' in row.get('notes', ''):
            continue
        
        # Translate war name
        old_name = row['wars']
        if old_name in WAR_NAME_TRANSLATIONS:
            row['wars'] = WAR_NAME_TRANSLATIONS[old_name]
            translated += 1
        else:
            print(f"  WARNING: No translation for: {old_name}")
        
        # Translate participation field
        old_part = row['participation']
        new_part = translate_participation(old_part)
        if new_part != old_part:
            row['participation'] = new_part
            participation_translated += 1

    print(f"War names translated: {translated}/262")
    print(f"Participation fields translated: {participation_translated}")
    
    with open(OUTPUT_CSV, 'w', newline='') as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    
    print(f"Written to {OUTPUT_CSV}")
    
    # Quick verification
    with open(OUTPUT_CSV) as f:
        reader = csv.DictReader(f)
        rows = list(reader)
    
    print("\n=== SAMPLE TRANSLATIONS ===")
    samples = ["Segunda Guerra Mundial", "Primera Guerra Mundial", "Guerra de Vietnam",
                "Guerra Civil Española", "Guerra de las Malvinas", "Guerra civil siria",
                "Guerra ruso-ucraniana", "Guerra de Corea", "Guerra del este de Ucrania"]
    for s in samples:
        matches = [r for r in rows if r['wars'] == s]
        if matches:
            r = matches[0]
            print(f"  {r['wars']:50s} part={r['participation'][:60]}")


if __name__ == '__main__':
    main()
